project_id = "detailflow"

[db]
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3100"
additional_redirect_urls = ["http://localhost:3100/auth/callback**"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
