import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/server";

const safeImage = z.string().refine((value) => /^\/images\/[A-Za-z0-9_-]+\.(jpg|jpeg|png|webp)$/.test(value) || /^services\/[A-Za-z0-9_-]+\.(jpg|jpeg|png|webp)$/.test(value), "Unsafe image key.");
const schema = z.object({ id: z.string().uuid().nullable().optional(), slug: z.string().regex(/^[a-z0-9-]+$/), name: z.string().min(1).max(120), eyebrow: z.string().max(120), description: z.string().min(1).max(1000), details: z.string().max(1000), duration_minutes: z.number().int().positive().max(2880), price_cents: z.number().int().nonnegative(), active: z.boolean(), display_order: z.number().int().min(0).max(100), image_url: safeImage.nullable().optional(), image_alt: z.string().max(240).optional().default("") });
async function getAdmin() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return { supabase, allowed: false }; const { data: allowed } = await supabase.rpc("is_admin"); return { supabase, allowed: allowed === true }; }
export async function GET() { if (!isSupabaseConfigured()) return NextResponse.json({ error: "Supabase is not configured." }, { status: 503 }); const { supabase, allowed } = await getAdmin(); if (!allowed) return NextResponse.json({ error: "Admin access required." }, { status: 403 }); const { data, error } = await supabase.from("services").select("id, slug, name, eyebrow, description, details, duration_minutes, price_cents, active, display_order, image_url, image_alt").order("display_order"); if (error) return NextResponse.json({ error: "Unable to load services." }, { status: 503 }); return NextResponse.json({ services: data ?? [] }, { headers: { "Cache-Control": "private, no-store" } }); }
export async function POST(request: Request) { if (!isSupabaseConfigured()) return NextResponse.json({ error: "Supabase is not configured." }, { status: 503 }); const { supabase, allowed } = await getAdmin(); if (!allowed) return NextResponse.json({ error: "Admin access required." }, { status: 403 }); let body: unknown; try { body = await request.json(); } catch { return NextResponse.json({ error: "Invalid request." }, { status: 400 }); } const parsed = schema.safeParse(body); if (!parsed.success) return NextResponse.json({ error: "Invalid service record." }, { status: 400 }); const { data, error } = await supabase.rpc("admin_upsert_service_with_image", { p_id: parsed.data.id ?? null, p_slug: parsed.data.slug, p_name: parsed.data.name, p_eyebrow: parsed.data.eyebrow, p_description: parsed.data.description, p_details: parsed.data.details, p_duration_minutes: parsed.data.duration_minutes, p_price_cents: parsed.data.price_cents, p_active: parsed.data.active, p_display_order: parsed.data.display_order, p_image_url: parsed.data.image_url ?? null, p_image_alt: parsed.data.image_alt }); if (error) return NextResponse.json({ error: "Unable to save service." }, { status: 409 }); return NextResponse.json({ service: data }); }
