import type { Metadata } from "next";
import Image from "next/image";
export const metadata: Metadata = { title: "Contact" };

export default function ContactPage() {
  return (
    <>
      <section className="bg-[#eff6ff] px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1fr_.75fr] lg:items-end"><div><p className="editorial-kicker text-[#2563eb]">Contact / studio desk</p><h1 className="display mt-5 max-w-4xl text-4xl font-semibold tracking-[-.045em] text-[#0b1739] sm:text-6xl">Let’s talk through the car.</h1></div><p className="max-w-md text-base leading-7 text-slate-600 lg:justify-self-end">Tell us what you’re driving, what you’ve noticed, and what you’re hoping for. We’ll point you in the right direction.</p></div></section>
      <section className="px-5 py-16 sm:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.72fr_1.28fr] lg:items-start"><div className="image-frame aspect-[4/3]"><Image src="/images/detailflow-handover-v2.png" alt="AI-generated illustrative handover scene with keys and a care towel" fill sizes="(max-width: 1024px) 100vw, 35vw" className="object-cover" /><p className="absolute bottom-4 left-4 bg-[#fffdfa]/90 px-3 py-2 text-[10px] font-bold uppercase tracking-[.14em] text-[#0b1739]">AI-generated portfolio concept</p></div><div className="lg:pt-1"><div className="grid gap-8 border-b border-slate-200 pb-8 sm:grid-cols-3"><div><p className="editorial-kicker text-[#2563eb]">Studio</p><p className="mt-3 text-sm leading-6 text-slate-700">19 Mercer Lane<br />Brooklyn, NY 11222</p></div><div><p className="editorial-kicker text-[#2563eb]">Hours</p><p className="mt-3 text-sm leading-6 text-slate-700">Tuesday–Saturday<br />8:00 am — 6:00 pm</p></div><div><p className="editorial-kicker text-[#2563eb]">Email</p><a className="mt-3 inline-block text-sm font-semibold text-[#2563eb] hover:text-[#1d4ed8]" href="mailto:hello@detailflow.demo">hello@detailflow.demo</a><p className="mt-2 text-xs leading-5 text-slate-500">Demo address · no email is sent from this preview</p></div></div><form className="pt-8" action="mailto:hello@detailflow.demo" method="post" encType="text/plain"><p className="text-base leading-7 text-slate-600">Share a little context and your email client will open a prepared message. Nothing is sent automatically from this preview.</p><div className="mt-8 grid gap-6 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Name<span className="mt-1 block text-xs font-normal text-slate-500">How should we address you?</span><input name="name" required placeholder="Your name" className="mt-2 field font-normal placeholder:text-slate-500" /></label><label className="text-sm font-medium text-slate-700">Email<span className="mt-1 block text-xs font-normal text-slate-500">Where can we reply?</span><input name="email" type="email" required placeholder="you@example.com" className="mt-2 field font-normal placeholder:text-slate-500" /></label></div><label className="mt-8 block text-sm font-medium text-slate-700">What can we help with?<span className="mt-1 block text-xs font-normal text-slate-500">Paint concerns, interior questions, or a custom scope.</span><textarea name="message" rows={5} required placeholder="Tell us what you’re seeing…" className="mt-3 field min-h-36 resize-y font-normal placeholder:text-slate-500" /></label><div className="mt-8 flex flex-wrap items-center gap-5"><button type="submit" className="action-primary inline-flex px-6 py-4 text-sm">Prepare email <span aria-hidden className="ml-4">↗</span></button><p className="text-xs leading-5 text-slate-500">Demo only · your email client handles the message.</p></div></form></div></div></section>
    </>
  );
}
