import type { Metadata } from "next";
import Image from "next/image";
export const metadata: Metadata = { title: "Contact" };

export default function ContactPage() {
  return (
    <>
      <section className="bg-[#eff6ff] px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_.75fr] lg:items-end"><div><p className="editorial-kicker text-[#2563eb]">Contact / studio desk</p><h1 className="display mt-6 max-w-4xl text-6xl font-semibold text-[#0b1739] sm:text-8xl">Questions are always welcome.</h1></div><p className="max-w-md text-lg leading-8 text-slate-600 lg:justify-self-end">Tell us what you’re driving, what you’ve noticed, and what you’re hoping for. We’ll point you in the right direction.</p></div></section>
      <section className="px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.7fr_1.3fr] lg:items-start"><div className="image-frame aspect-[4/5] lg:aspect-[3/4]"><Image src="/images/detailflow-paint-detail.png" alt="AI-generated illustrative close-up of water on a vehicle surface" fill sizes="(max-width: 1024px) 100vw, 35vw" className="object-cover" /><p className="absolute bottom-4 left-4 bg-[#fffdfa]/90 px-3 py-2 text-[10px] font-bold uppercase tracking-[.14em] text-[#0b1739]">AI-generated portfolio concept</p></div><div className="lg:pt-3"><div className="grid gap-8 border-b border-slate-200 pb-10 sm:grid-cols-3"><div><p className="editorial-kicker text-[#2563eb]">Studio</p><p className="mt-3 text-sm leading-6 text-slate-700">19 Mercer Lane<br />Brooklyn, NY 11222</p></div><div><p className="editorial-kicker text-[#2563eb]">Hours</p><p className="mt-3 text-sm leading-6 text-slate-700">Tuesday–Saturday<br />8:00 am — 6:00 pm</p></div><div><p className="editorial-kicker text-[#2563eb]">Email</p><a className="mt-3 inline-block text-sm font-semibold text-[#2563eb] hover:text-[#1d4ed8]" href="mailto:hello@detailflow.demo">hello@detailflow.demo</a><p className="mt-2 text-xs leading-5 text-slate-500">Demo address · no email is sent from this preview</p></div></div><form className="pt-10" action="mailto:hello@detailflow.demo" method="post" encType="text/plain"><div className="grid gap-6 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Name<input name="name" required className="mt-3 w-full border-0 border-b border-slate-300 bg-transparent px-0 py-3 font-normal focus:border-blue-600 focus:ring-0" /></label><label className="text-sm font-medium text-slate-700">Email<input name="email" type="email" required className="mt-3 w-full border-0 border-b border-slate-300 bg-transparent px-0 py-3 font-normal focus:border-blue-600 focus:ring-0" /></label></div><label className="mt-8 block text-sm font-medium text-slate-700">What can we help with?<textarea name="message" rows={6} required className="mt-3 w-full resize-y border-0 border-b border-slate-300 bg-transparent px-0 py-3 font-normal focus:border-blue-600 focus:ring-0" /></label><div className="mt-8 flex flex-wrap items-center gap-5"><button type="submit" className="inline-flex bg-[#2563eb] px-6 py-4 text-sm font-semibold text-white hover:bg-[#1d4ed8]">Prepare email <span aria-hidden className="ml-4">↗</span></button><p className="text-xs leading-5 text-slate-500">This preview opens your email client. No message is sent automatically.</p></div></form></div></div></section>
    </>
  );
}
