import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/server";
import { localDateTimeToUtcIso } from "@/lib/timezone";

const issueSchema = z.object({ customer_id: z.string().uuid(), code: z.string().trim().min(4).max(40).regex(/^[A-Za-z0-9-]+$/), discount_kind: z.enum(["fixed", "percent"]), discount_value: z.number().int().positive(), expires_on: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(), expires_at: z.string().datetime({ offset: true }).optional(), service_id: z.string().uuid().nullable().optional() }).refine((value) => Boolean(value.expires_on || value.expires_at), "Expiry is required.");
async function getAdmin() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return { supabase, allowed: false }; const { data: allowed } = await supabase.rpc("is_admin"); return { supabase, allowed: allowed === true }; }
export async function GET() { if (!isSupabaseConfigured()) return NextResponse.json({ vouchers: [] }); const { supabase, allowed } = await getAdmin(); if (!allowed) return NextResponse.json({ error: "Admin access required." }, { status: 403 }); const { data, error } = await supabase.rpc("admin_list_vouchers"); if (error) return NextResponse.json({ error: "Unable to load vouchers." }, { status: 503 }); return NextResponse.json({ vouchers: data ?? [] }, { headers: { "Cache-Control": "private, no-store" } }); }
export async function POST(request: Request) { if (!isSupabaseConfigured()) return NextResponse.json({ error: "Supabase is not configured." }, { status: 503 }); const { supabase, allowed } = await getAdmin(); if (!allowed) return NextResponse.json({ error: "Admin access required." }, { status: 403 }); let raw: unknown; try { raw = await request.json(); } catch { return NextResponse.json({ error: "Invalid request." }, { status: 400 }); } const parsed = issueSchema.safeParse(raw); if (!parsed.success || (parsed.data.discount_kind === "percent" && parsed.data.discount_value > 100)) return NextResponse.json({ error: "Check the customer, discount, and expiry." }, { status: 400 }); let expiresAt = parsed.data.expires_at; if (parsed.data.expires_on) { try { const settings = await supabase.from("business_settings").select("timezone").eq("id", true).maybeSingle(); const [year, month, day] = parsed.data.expires_on.split("-").map(Number); const nextDate = new Date(Date.UTC(year, month - 1, day + 1)).toISOString().slice(0, 10); const timeZone = settings.data?.timezone ?? "America/New_York"; localDateTimeToUtcIso(`${parsed.data.expires_on}T00:00`, timeZone); expiresAt = localDateTimeToUtcIso(`${nextDate}T00:00`, timeZone); } catch { return NextResponse.json({ error: "Choose a valid expiry date." }, { status: 400 }); } } if (!expiresAt) return NextResponse.json({ error: "Check the customer, discount, and expiry." }, { status: 400 }); const { data, error } = await supabase.rpc("admin_issue_voucher", { p_customer_id: parsed.data.customer_id, p_code: parsed.data.code.toUpperCase(), p_discount_kind: parsed.data.discount_kind, p_discount_value: parsed.data.discount_value, p_expires_at: expiresAt, p_service_id: parsed.data.service_id ?? null }); if (error) return NextResponse.json({ error: error.message.includes("already exists") ? "That voucher code already exists." : "Unable to issue voucher." }, { status: 409 }); return NextResponse.json({ voucher: data }, { status: 201 }); }
export async function PATCH(request: Request) { if (!isSupabaseConfigured()) return NextResponse.json({ error: "Supabase is not configured." }, { status: 503 }); const { supabase, allowed } = await getAdmin(); if (!allowed) return NextResponse.json({ error: "Admin access required." }, { status: 403 }); let raw: unknown; try { raw = await request.json(); } catch { return NextResponse.json({ error: "Invalid request." }, { status: 400 }); } const parsed = z.object({ id: z.string().uuid() }).safeParse(raw); if (!parsed.success) return NextResponse.json({ error: "Invalid voucher." }, { status: 400 }); const { data, error } = await supabase.rpc("admin_revoke_voucher", { p_voucher_id: parsed.data.id }); if (error) return NextResponse.json({ error: "Unable to revoke voucher." }, { status: 409 }); return NextResponse.json({ voucher: data }); }
