import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/server";
import { localDateTimeToUtcIso } from "@/lib/timezone";
const localDateTime = z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/);
const schema = z.object({ id: z.string().uuid().nullable().optional(), starts_at: z.string().datetime().or(localDateTime), ends_at: z.string().datetime().or(localDateTime), reason: z.string().trim().min(2).max(240), active: z.boolean().default(true) });
async function getAdmin() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return { supabase, allowed: false }; const { data: allowed } = await supabase.rpc("is_admin"); return { supabase, allowed: allowed === true }; }
export async function GET() { if (!isSupabaseConfigured()) return NextResponse.json({ error: "Supabase is not configured." }, { status: 503 }); const { supabase, allowed } = await getAdmin(); if (!allowed) return NextResponse.json({ error: "Admin access required." }, { status: 403 }); const { data, error } = await supabase.rpc("admin_list_blocks"); if (error) return NextResponse.json({ error: "Unable to load blocked periods." }, { status: 503 }); return NextResponse.json({ blocks: data ?? [] }); }
export async function POST(request: Request) { if (!isSupabaseConfigured()) return NextResponse.json({ error: "Supabase is not configured." }, { status: 503 }); const { supabase, allowed } = await getAdmin(); if (!allowed) return NextResponse.json({ error: "Admin access required." }, { status: 403 }); let body: unknown; try { body = await request.json(); } catch { return NextResponse.json({ error: "Invalid request." }, { status: 400 }); } const parsed = schema.safeParse(body); if (!parsed.success) return NextResponse.json({ error: "Invalid blocked interval." }, { status: 400 }); try { const { data: settings } = await supabase.from("business_settings").select("timezone").eq("id", true).maybeSingle(); const timeZone = settings?.timezone ?? "America/New_York"; const startsAt = localDateTimeToUtcIso(parsed.data.starts_at, timeZone); const endsAt = localDateTimeToUtcIso(parsed.data.ends_at, timeZone); if (new Date(endsAt) <= new Date(startsAt)) return NextResponse.json({ error: "End must follow start." }, { status: 400 }); const { data, error } = await supabase.rpc("admin_upsert_block", { p_id: parsed.data.id ?? null, p_starts_at: startsAt, p_ends_at: endsAt, p_reason: parsed.data.reason, p_active: parsed.data.active }); if (error) return NextResponse.json({ error: "Unable to save blocked interval." }, { status: 409 }); return NextResponse.json({ block: data }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Invalid local time." }, { status: 400 }); } }
