import Image from "next/image";
import Link from "next/link";
import { BeforeAfter } from "@/components/before-after";
import { ServiceCard } from "@/components/service-card";
import { getPublicServices } from "@/lib/public-services";
import { serviceImage } from "@/data/services";

const stockImages = {
  hero: "/images/detailflow-cinematic-hero.png",
  interior: "/images/detailflow-interior.png",
  detail: "/images/detailflow-paint-detail.png",
};

export default async function Home() {
  const services = await getPublicServices();
  return (
    <>
      <section className="bg-[#fffdfa] px-4 py-4 text-white sm:px-6 lg:px-8">
        <div className="relative mx-auto min-h-[640px] max-w-[1440px] overflow-hidden bg-[#0b1739] sm:min-h-[700px]">
          <Image src={stockImages.hero} alt="Royal blue coupe in a deep navy studio" fill priority sizes="100vw" className="object-cover object-center" />
          <div className="absolute inset-0 bg-gradient-to-r from-[#0b1739]/95 via-[#0b1739]/48 to-transparent" />
          <div className="absolute inset-0 bg-gradient-to-t from-[#0b1739]/85 via-transparent to-[#0b1739]/10" />
          <div className="relative flex min-h-[640px] flex-col justify-between p-6 sm:min-h-[700px] sm:p-10 lg:p-14">
            <div className="flex items-start justify-between gap-6"><span className="editorial-kicker border border-white/35 px-3 py-2 text-blue-100">Portfolio demo · fictional studio</span><span className="hidden text-right text-[10px] font-bold uppercase tracking-[.18em] text-white/70 sm:block">Brooklyn / One bay<br />Tue—Sat / 08—18</span></div>
            <div className="max-w-3xl"><p className="editorial-kicker flex items-center gap-3 text-blue-200"><span className="h-px w-10 bg-blue-300" />Independent detailing studio</p><h1 className="display mt-7 text-6xl font-medium sm:text-7xl lg:text-[7rem]">Every surface.<br /><span className="text-blue-300">Considered.</span></h1><p className="mt-8 max-w-lg text-base leading-7 text-white/75 sm:text-lg">Thoughtful care for cars you plan to keep. Clear scope, careful hands, and a finish that holds its own in any light.</p><div className="mt-8 flex flex-wrap gap-6"><Link href="/booking" className="inline-flex items-center bg-[#2563eb] px-5 py-3 text-sm font-semibold text-white hover:bg-[#1d4ed8]">Book a detail <span aria-hidden className="ml-3">↗</span></Link><Link href="#menu" className="border-b border-white/50 pb-2 text-sm font-semibold text-white/80 hover:border-white">Explore the menu <span aria-hidden className="ml-3">↓</span></Link></div></div>
            <div className="grid gap-5 border-t border-white/25 pt-5 text-xs text-white/70 sm:grid-cols-3"><div><span className="block text-white">01</span>Condition first</div><div><span className="block text-white">02</span>One car at a time</div><div><span className="block text-white">03</span>A calm handover</div></div>
          </div>
        </div>
      </section>

      <section className="mx-auto grid max-w-[1440px] gap-12 px-5 py-24 sm:px-8 lg:grid-cols-[.85fr_1.15fr] lg:gap-24 lg:py-36">
        <div><p className="editorial-kicker text-[#2563eb]">A quieter kind of detailing</p><h2 className="display mt-7 max-w-xl text-5xl font-semibold text-[#0b1739] sm:text-7xl">The finish starts before the polish.</h2></div>
        <div className="max-w-2xl"><p className="text-xl leading-9 text-slate-700 sm:text-2xl">We begin with a walkaround, listen to what you’ve noticed, and build the work around the actual condition of your car.</p><p className="mt-7 text-base leading-8 text-slate-600">That means fewer promises, better decisions, and an honest handover. DetailFlow is a fictional portfolio studio built around the feeling of a small room where every surface gets its moment.</p><Link href="/about" className="mt-9 inline-flex border-b border-[#2563eb] pb-2 text-sm font-bold text-[#2563eb]">See our approach <span aria-hidden className="ml-3">↗</span></Link></div>
      </section>

      <section id="menu" className="border-y border-slate-200 bg-[#f5f7fb] px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="editorial-kicker text-[#2563eb]">The studio menu</p><h2 className="display mt-6 text-5xl font-semibold text-[#0b1739] sm:text-7xl">Choose your<br />starting point.</h2></div><Link href="/services" className="border-b border-[#2563eb] pb-2 text-sm font-bold text-[#2563eb]">View all services <span aria-hidden className="ml-3">↗</span></Link></div><div className="mt-16 grid gap-x-7 gap-y-14 lg:grid-cols-3">{services.length ? services.map((service, index) => <ServiceCard key={service.slug} service={service} image={serviceImage(service.slug)} featured={index === 1} />) : <p className="text-sm text-slate-600 lg:col-span-3">No active service records are available yet. Connect Supabase to publish the live menu.</p>}</div></div></section>

      <section className="mx-auto grid max-w-[1440px] gap-12 px-5 py-24 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:items-end lg:gap-24 lg:py-36"><div className="image-frame aspect-[4/5] lg:aspect-[4/4.2]"><Image src={stockImages.detail} alt="AI-generated illustrative close-up of automotive paint and reflected light" fill sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover" /><span className="absolute bottom-5 left-5 bg-[#fffdfa]/90 px-3 py-2 text-[10px] font-bold uppercase tracking-[.15em] text-[#0b1739]">AI-generated portfolio concept</span></div><div className="pb-2 lg:pb-12"><p className="editorial-kicker text-[#2563eb]">Our point of view</p><h2 className="display mt-6 text-5xl font-semibold text-[#0b1739] sm:text-7xl">Small studio.<br />Deep attention.</h2><div className="mt-9 space-y-7 border-t border-slate-300 pt-7"><div className="grid grid-cols-[44px_1fr] gap-4"><span className="text-sm font-bold text-[#2563eb]">01</span><p className="text-sm leading-7 text-slate-600">We take fewer cars each day so every surface gets the time it deserves.</p></div><div className="grid grid-cols-[44px_1fr] gap-4 border-t border-slate-200 pt-7"><span className="text-sm font-bold text-[#2563eb]">02</span><p className="text-sm leading-7 text-slate-600">Clear packages, honest recommendations, and a plan you can understand.</p></div></div><Link href="/about" className="mt-10 inline-flex border-b border-[#0b1739] pb-2 text-sm font-bold text-[#0b1739]">Our approach <span aria-hidden className="ml-3">↗</span></Link></div></section>

      <section className="bg-[#0b1739] px-5 py-24 text-white sm:px-8 lg:py-32"><div className="mx-auto max-w-[1440px]"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><div><p className="editorial-kicker text-blue-300">Illustrative comparison</p><h2 className="display mt-6 text-5xl font-semibold sm:text-7xl">See the care<br />in the surface.</h2><p className="mt-7 max-w-sm text-sm leading-7 text-blue-100/70">A fictional before / after concept built from AI-generated portfolio imagery. It is not a customer result.</p></div><BeforeAfter /></div></div></section>

      <section className="mx-auto max-w-[1440px] px-5 py-24 sm:px-8 lg:py-32"><div className="grid gap-8 border-t border-slate-300 pt-8 md:grid-cols-3"><div><p className="editorial-kicker text-[#2563eb]">01 / Choose</p><h3 className="mt-5 text-2xl font-semibold tracking-[-.04em] text-[#0b1739]">Start with the right scope.</h3><p className="mt-4 text-sm leading-7 text-slate-600">Browse the menu and choose the finish that fits the car in front of you.</p></div><div><p className="editorial-kicker text-[#2563eb]">02 / Find a time</p><h3 className="mt-5 text-2xl font-semibold tracking-[-.04em] text-[#0b1739]">See the real calendar.</h3><p className="mt-4 text-sm leading-7 text-slate-600">Availability comes from the one-bay studio schedule, in local studio time.</p></div><div><p className="editorial-kicker text-[#2563eb]">03 / Hand over</p><h3 className="mt-5 text-2xl font-semibold tracking-[-.04em] text-[#0b1739]">Leave the keys with us.</h3><p className="mt-4 text-sm leading-7 text-slate-600">We’ll walk you through what changed and how to keep it that way.</p></div></div></section>

      <section className="bg-[#eff6ff] px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto max-w-[1100px]"><p className="editorial-kicker text-[#2563eb]">Before you arrive</p><h2 className="display mt-6 max-w-xl text-5xl font-semibold text-[#0b1739] sm:text-7xl">A few clear answers.</h2><div className="mt-14 divide-y divide-blue-200 border-y border-blue-200">{[["How far ahead can I book?","The live calendar opens 60 days ahead in the studio’s local time zone."],["What if I need to change plans?","You can cancel or reschedule up to 24 hours before your appointment from your account."],["Do you work on all makes?","Yes. Tell us what you drive and what you’ve noticed; we’ll recommend the right scope."],["Where are you located?","DetailFlow is a fictional preview studio at 19 Mercer Lane in Brooklyn."]].map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 text-lg font-semibold text-[#0b1739]"><span>{question}</span><span className="text-2xl font-light text-[#2563eb] transition-transform group-open:rotate-45">+</span></summary><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-600">{answer}</p></details>)}</div></div></section>

      <section className="bg-[#0b1739] px-5 py-24 text-white sm:px-8 lg:py-32"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-10 md:flex-row md:items-end"><div><p className="editorial-kicker text-blue-300">Ready when you are</p><h2 className="display mt-6 max-w-3xl text-6xl font-semibold sm:text-8xl">Take the long way home.</h2></div><Link href="/booking" className="inline-flex items-center bg-[#2563eb] px-5 py-3 text-sm font-semibold text-white hover:bg-[#1d4ed8]">Find an appointment <span aria-hidden className="ml-3">↗</span></Link></div></section>
      <p className="sr-only">Photography throughout this page is illustrative stock imagery or AI-generated portfolio concept imagery and does not depict DetailFlow customers or verified results.</p>
    </>
  );
}
