"use client";
import Link from "next/link";
import { useState } from "react";
export function SiteHeader() {
  const [open, setOpen] = useState(false);
  const nav = [["Services", "/services"], ["Gallery", "/gallery"], ["Our approach", "/about"], ["Contact", "/contact"]];
  return <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><Link href="/" className="group flex items-center gap-3" onClick={() => setOpen(false)} aria-label="DetailFlow home"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#0b1739] text-sm font-black tracking-tight text-white">DF</span><span><span className="block text-[15px] font-bold tracking-[.22em] text-[#0b1739]">DETAILFLOW</span><span className="block text-[10px] font-medium uppercase tracking-[.18em] text-slate-500">Auto detailing studio</span></span></Link><nav className="hidden items-center gap-7 lg:flex" aria-label="Primary navigation">{nav.map(([label, href]) => <Link key={href} href={href} className="whitespace-nowrap text-sm font-medium text-slate-600 transition hover:text-[#2563eb]">{label}</Link>)}<Link href="/login?next=/account" className="whitespace-nowrap text-sm font-medium text-slate-600 transition hover:text-[#2563eb]">Sign in</Link><Link href="/booking" className="whitespace-nowrap rounded-full bg-[#2563eb] px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-blue-200 transition hover:bg-[#1d4ed8]">Book a detail</Link></nav><button type="button" onClick={() => setOpen(!open)} className="rounded-lg p-2 text-[#0b1739] lg:hidden" aria-expanded={open} aria-label={open ? "Close menu" : "Open menu"}><span className="block h-0.5 w-6 bg-current" /><span className="my-1.5 block h-0.5 w-6 bg-current" /><span className="block h-0.5 w-6 bg-current" /></button></div>{open && <nav className="border-t border-slate-100 bg-white px-5 pb-5 pt-3 lg:hidden" aria-label="Mobile navigation">{nav.map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)} className="block border-b border-slate-100 py-3 text-sm font-medium text-slate-700">{label}</Link>)}<Link href="/login?next=/account" onClick={() => setOpen(false)} className="block border-b border-slate-100 py-3 text-sm font-medium text-slate-700">Sign in</Link><Link href="/booking" onClick={() => setOpen(false)} className="mt-4 block rounded-full bg-[#2563eb] px-5 py-3 text-center text-sm font-semibold text-white">Book a detail</Link></nav>}</header>;
}

